var books = new Array(
        {
            "title": "될 수 있어! SE",
            "labelColor": "#d67310",
            "originalTitle": "なれる！ SE",
            "author": "나츠미 코지",
            "oAuthor": "夏海 公司",
            "translator": "김경훈",
        },
        {
            "title": "제로의 사역마",
            "labelColor": "",
            "originalTitle": "ゼロの使い魔",
            "author": "ヤマグチノボル",
            "oAuthor": "",
            "translator": "윤영의"
        },
        {
            "title": "은톨이 그녀는 신입니다",
            "labelColor": "",
            "originalTitle": "ひきこもりの彼女は神なのです",
            "author": "스에바시 켄",
            "oAuthor": "すえばし けん",
            "translator": "박정원"
        },
        {
            "title": "사쿠라코 씨의 발밑에는 시체가 묻혀 있다",
            "labelColor": "",
            "originalTitle": "櫻子さんの足下には死体が埋まっている",
            "author": "오타 시오리",
            "oAuthor": "太田 紫織",
            "translator": "박춘상",
        },
        {
           "title": "이 멋진 세계에 축복을!",
            "labelColor": "",
            "originalTitle": "この素晴らしい世界に祝福を!",
            "author": "아카츠키 나츠메",
            "oAuthor": "暁 なつめ",
            "translator": "이승원",
        },
        {
            "title": "던전에서 만남을 추구하면 안 되는 걸까",
            "labelColor": "",
            "originalTitle": "ダンジョンに出會いを求めるのは間違っているだろうか",
            "author": "오모리 후지노",
            "oAuthor": "大森 藤ノ",
            "translator": "김완",
        },
        {
            "title": "역시 내 청춘 러브코메디는 잘못됐다.",
            "labelColor": "",
            "originalTitle": "はり俺の青春ラブコメはまちがっている。",
            "author": "	와타리 와타루",
            "oAuthor": "渡 航",
            "translator": "박정원",
        },
        {
            "title": "시원찮은 그녀를 위한 육성방법",
            "labelColor": "",
            "originalTitle": "冴さえない彼女ヒロインの育そだてかた",
            "author": "마루토 후미아키",
            "oAuthor": "丸戸史明",
            "translator": "이승원",
        },
        {
            "title": "재와 환상의 그림갈",
            "labelColor": "",
            "originalTitle": "灰と幻想のグリムガル",
            "author": "주몬지 아오",
            "oAuthor": "十文字 青",
            "translator": "이형진",
        },
        {
            "title": "무직전생 ~이세계에 갔으면 최선을 다한다~",
            "labelColor": "",
            "originalTitle": "無職転生 ~異世界行ったら本気だす~",
            "author": "리후진 나 마고노테",
            "oAuthor": "理不尽な孫の手",
            "translator": "한신남",
        }
);
